function [nu_deg,cos_beta_xm,cos_beta_xp,cos_beta_ym,cos_beta_yp,cos_beta_zm,cos_beta_zp] = aaf_importarCosenos(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [NU_DEG,COS_BETA_XM,COS_BETA_XP,COS_BETA_YM,COS_BETA_YP,COS_BETA_ZM,COS_BETA_ZP]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [NU_DEG,COS_BETA_XM,COS_BETA_XP,COS_BETA_YM,COS_BETA_YP,COS_BETA_ZM,COS_BETA_ZP]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [nu_deg,cos_beta_xm,cos_beta_xp,cos_beta_ym,cos_beta_yp,cos_beta_zm,cos_beta_zp] = importfile('CosenosLN1200.txt',3, 1003);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/02/24 18:01:17

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
nu_deg = dataArray{:, 1};
cos_beta_xm = dataArray{:, 2};
cos_beta_xp = dataArray{:, 3};
cos_beta_ym = dataArray{:, 4};
cos_beta_yp = dataArray{:, 5};
cos_beta_zm = dataArray{:, 6};
cos_beta_zp = dataArray{:, 7};


